platform :ios, '14.3'
inhibit_all_warnings!
use_frameworks!

abstract_target 'BaseApp' do
  pod 'SwiftLint'
  pod 'Swinject'

  target 'SimpleGithubSearch' do
  end

  target 'SimpleGithubSearchUnitTests' do
    pod 'Quick'
    pod 'Nimble'
  end

end
